version: '3.9'

# below is the format of DATABASE_URL in .env file
# DATABASE_URL=mysql://root:mySQL@db:3306/testdb

services:
  db:
    image: mysql:latest
    restart: always
    container_name: mySQL
    ports:
      - "3307:3306"
    env_file:
      - .env.test.local
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:7.2.5-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    env_file:
      - .env.test.local
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: goreto
  #   restart: always # on crash restart the container
  #   env_file:
  #     - .env.test.local
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - redis

volumes:
  mysql:
  cache:
    driver: local
